server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: ${SECRET_KEY}

kakao:
  key:
    client-id: ${REST_API_KEY}
  redirect-uri: ${REDIRECT_URI}

logging:
  level:
    org.hibernate.SQL: debug          # SQL 쿼리 확인
    org.hibernate.orm.jdbc.bind: trace    # 쿼리 파라미터 확인
    com.letter: debug                 # 프로젝트 패키지의 모든 로그

alice:
  api:
    url: ${ALICE_URL}
    key: ${API-KEY}
