name: Backend Deploy

on:
  push:
    branches:
      - "main"
      - "5-feat-deployment"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 환경변수 설정
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_SCHEMA }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      - name: Gradle 빌드
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test  # 테스트 제외 (이미 CI에서 검증됨)

      - name: 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "~/app"

      - name: 애플리케이션 재시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "=== System Info ==="
            df -h
            free -m
            
            echo "=== Current Directory ==="
            pwd
            ls -la
            
            echo "=== App Directory ==="
            cd ~/app
            pwd
            ls -la
            
            echo "=== Java Version ==="
            java -version
            
            echo "=== Kill Old Process ==="
            pkill -f 'java -jar' || true
            
            echo "=== Start Application ==="
            nohup java -jar *.jar > app.log 2>&1 &
            APP_PID=$!
            echo $APP_PID > app.pid
            
            echo "=== Initial Log Check ==="
            sleep 5
            cat app.log
            
            echo "=== Process Status ==="
            ps aux | grep java
            
            echo "=== Final Check ==="
            if ps -p $APP_PID > /dev/null; then
              echo "Process is running"
              exit 0
            else
              echo "Process failed to start"
              exit 1
            fi