name: Backend Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:    # 수동 트리거 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 환경변수 설정
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_SCHEMA }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      - name: Gradle 빌드
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test  # 테스트 제외 (이미 CI에서 검증됨)

      - name: 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "~/app"

      - name: 애플리케이션 재시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 기존 프로세스 종료
            pkill -f 'java -jar' || true
            
            # app 디렉토리로 이동
            cd ~/app
            
            # jar 파일 실행 권한 부여
            chmod +x *.jar
            
            # 애플리케이션 실행 및 PID 저장
            nohup java -jar *.jar > app.log 2>&1 & echo $! > app.pid
            
            # 프로세스 시작 확인을 위한 대기
            sleep 10
            
            # 프로세스 실행 상태 확인
            if ps -p $(cat app.pid) > /dev/null; then
              echo "애플리케이션이 성공적으로 시작되었습니다"
              exit 0
            else
              echo "애플리케이션 시작 실패"
              echo "로그 확인:"
              cat app.log
              exit 1
            fi