name: Backend Deploy

on:
  push:
    branches:
      - "main"
      - "5-feat-deployment"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 환경변수 설정
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_SCHEMA }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      - name: Gradle 빌드
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test  # 테스트 제외 (이미 CI에서 검증됨)

      - name: 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "~/app"

      - name: 애플리케이션 재시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          command_timeout: 30m
          script: |
            echo "=== Setup Directories ==="
            cd ~/app
            
            echo "=== Kill Old Process ==="
            pkill -f 'java -jar' || true
            sleep 5
            
            echo "=== Start Application ==="
            # 절대 경로 사용
            APP_DIR="/home/***/app"
            LOG_FILE="$APP_DIR/app.log"
            PID_FILE="$APP_DIR/app.pid"
            JAR_FILE="$APP_DIR/build/libs/letter-0.0.1-SNAPSHOT.jar"
            
            # 로그 파일 생성
            touch "$LOG_FILE"
            
            echo "Starting application from $(pwd)"
            echo "Using JAR: $JAR_FILE"
            echo "Log file: $LOG_FILE"
            
            # nohup으로 실행
            nohup java -jar "$JAR_FILE" > "$LOG_FILE" 2>&1 &
            
            # PID 저장
            APP_PID=$!
            echo $APP_PID > "$PID_FILE"
            
            echo "Started with PID: $APP_PID"
            
            # 프로세스 확인
            sleep 5
            if ps -p $APP_PID > /dev/null; then
              echo "Process is running"
              echo "Recent logs:"
              tail -n 20 "$LOG_FILE"
              exit 0
            else
              echo "Process failed to start"
              echo "Error logs:"
              cat "$LOG_FILE"
              exit 1
            fi