name: Backend Deploy

on:
  push:
    branches:
      - "main"
      - "5-feat-deployment"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 환경변수 설정
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_SCHEMA }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      - name: Gradle 빌드
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "~/app"

      - name: 애플리케이션 재시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/app
            
            echo "=== Kill Old Process ==="
            pkill -f 'java -jar' || true
            sleep 2
            
            echo "=== Start Application ==="
            JAR_FILE="build/libs/letter-0.0.1-SNAPSHOT.jar"
            
            # application.yml에 포트가 이미 설정되어 있으므로 -Dserver.port 제거
            nohup java -jar "$JAR_FILE" > app.log 2>&1 & disown
            
            # 프로세스 확인
            sleep 5
            if pgrep -f 'java -jar'; then
              echo "Application started successfully"
              echo "=== Port Status ==="
              netstat -tulpn | grep 8081
              tail -n 20 app.log
              exit 0
            else
              echo "Application failed to start"
              cat app.log
              exit 1
            fi